[package]
name = "bflags"
version = "0.2.0"
edition = "2018"
authors = ["Daniel P. Teberian"]
categories = ["no-std", "embedded-development"]
license = "Apache-2.0"
description = "An alternative to bitflags."
